server:
  forward-headers-strategy: framework
  port: 4998
  servlet:
    context-path: /
  error:
    include-message: always
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "prometheus", "bindings", "beans", "env", "loggers", "streamsbindings", "mappings","flyway" ]
app:
  name: TurnQuest Version Vi Integrated GIS Setups System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: https://evolve.keycloak.caavagroup.com/realms/geminia
  rolesClaim: roles
  locale:
    baseName: i18n/messages
    defaultLang: en
spring:
  sleuth:
    sampler:
      probability: 1.0
  messages:
    basename: i18n/messages
  application:
    name: gis-ticketing-service
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  management:
    zipkin:
      tracing:
        endpoint: http://10.176.18.27:9411
  cloud:
    config:
      import-check:
        enabled: false
      server:
        git:
          uri: https://github.com/turnkeyafrica/turnquest-v6
          searchPaths: premium-computation-engine-configs
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticketing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resource:
        id: geminia
        token-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token
        authorization-uri: ${app.auth.server.realm-url}/protocol/openid-connect/auth
        userinfo-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
        token-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token/introspect
        user-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.server.realm-url}
          jwk-set-uri: ${app.auth.server.realm-url}/protocol/openid-connect/certs
  flyway:
    locations: classpath:/db/migration/oracle
    baseline-on-migrate: false #NEVER CHANGE BASELINE TO TRUE
    validate-on-migrate: false #true to populate local DB
    table: schema_version
    enabled: false
    out-of-order: true
    ignore-migration-patterns: false

defaultTenant: turnquest
# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://10.176.18.211:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
instanceId: gis-ticketing-service
env: environment

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{tenantId:-gis}] %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    name: ./logs/${spring.application.name}.log

management:
  endpoints:
    web:
      exposure:
        include: "*"

misc:
  currencies:
    base: 313
    currency_rate_extension_days: 30


camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All
    database:
      schema-update: "true"    # ✅ quoted to ensure it binds correctly in YAML
    auto-deployment-enabled: true
    history-level: full
    deployment-resource-pattern: "classpath*:processes/*.bpmn"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /gis/ticketing/v3/api-docs/swagger-config
    urls:
      - url: /gis/ticketing/v3/api-docs
        name: GIS TICKETING API
#  server-url: /gis/ticketing

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_GIS
        password: GIS_2026
        driver-class-name: oracle.jdbc.OracleDriver
#    heritage:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.91:1521/HERITAGE
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
#    heritage19c:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.91:1522/heritage19c
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
#    v6test:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.70:18000/TQV6
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
