server:
  forward-headers-strategy: framework
  port: 4020
  servlet:
    context-path: /
  error:
    include-message: always
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "prometheus", "bindings", "beans", "env", "loggers", "streamsbindings", "mappings","flyway" ]
app:
  name: TurnQuest Version Vi Integrated GIS Setups System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: https://evolve.staging.caavagroup.com/realms/geminia
  rolesClaim: roles
  locale:
    baseName: i18n/messages
    defaultLang: en
spring:
  sleuth:
    sampler:
      probability: 1.0
  messages:
    basename: i18n/messages
  application:
    name: premium-computation-service
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      allow-pool-suspension: true
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  management:
    zipkin:
      tracing:
        endpoint: http://10.176.18.27:9411
  cloud:
    config:
      import-check:
        enabled: false
      server:
        git:
          uri: https://github.com/turnkeyafrica/turnquest-v6
          searchPaths: premium-computation-engine-configs
      #kafka:
      # consumer:
      # auto-offset-reset: earliest
    # change this property if you are using your own Kafka cluster or your Docker IP is different
    #bootstrap-servers: ${kafka:localhost:9092}
    #client-id: premium-computation-engine
  security:
    oauth2:
      resource:
        id: geminia
        token-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/token
        authorization-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/auth
        userinfo-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/userinfo
        token-info-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/token/introspect
        user-info-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          issuer-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia
          jwk-set-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/certs
  flyway:
    locations: classpath:/db/migration/oracle
    baseline-on-migrate: false #NEVER CHANGE BASELINE TO TRUE
    validate-on-migrate: false #true to populate local DB
    table: schema_version
    enabled: false
    out-of-order: true
    ignore-migration-patterns: false
  sql:
    init:
      mode: always

defaultTenant: turnquest
# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://10.176.18.211:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
instanceId: gis-setups-service-instance
env: environment

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    name: ./logs/${spring.application.name}.log

management:
  endpoints:
    web:
      exposure:
        include: "*"

misc:
  currencies:
    base: 313
    currency_rate_extension_days: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /premium/computation/v3/api-docs/swagger-config
    urls:
      - url: /premium/computation/v3/api-docs
        name: GIS PREMIUM COMPUTATION API
#  server-url: /premium/computation

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_GIS
        password: GIS_2026
        driver-class-name: oracle.jdbc.OracleDriver

 turnquest:
  api:
    basePath:
      v1: "/api/v1"
      v2: "/api/v2"
  clients:
    crm:
      base-url: http://crm-service
      setupsService: http://crm-setups-service
      setups: http://crm-setups-service
    crm-setups:
      base-url: http://crm-setups-service
    crm-accounts:
      base-url: http://crm-accounts-service
    crm-useradmin:
      base-url: http://crm-user-administration-service
    setups:
      base-url: http://gis-setups-service
    premium-computation-engine:
      base-url: http://premium-computation-service
    notification-service:
      base-url: http://turnquest-notification-service
    underwriting-service:
      base-url: http://gis-underwriting-service
    commons-service:
      base-url: http://gis-commons-service
    ticketing-service:
      base-url: http://gis-ticketing-service
    quotation-service:
      base-url: http://gis-quotation-service
    alfresco-service:
      base-url: http://alfresco-service
    gis:
      setups:
        service: http://gis-setups-service


