server:
  forward-headers-strategy: framework
  port: 4011
  servlet:
    context-path: /
  error:
    include-message: always
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "prometheus", "bindings", "beans", "env", "loggers", "streamsbindings", "mappings","flyway" ]
app:
  name: TurnQuest Version Vi Integrated GIS Setups System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: https://evolve.keycloak.caavagroup.com/realms/geminia
  rolesClaim: roles
  locale:
    baseName: i18n/messages
    defaultLang: en
spring:
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    property-naming-strategy: SNAKE_CASE
  messages:
    basename: i18n/messages
  application:
    name: gis-setups-service
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  management:
    zipkin:
      tracing:
        endpoint: http://10.176.18.27:9411
  cloud:
    config:
      import-check:
        enabled: false
      server:
        git:
          uri: https://github.com/turnkeyafrica/turnquest-v6
          searchPaths: gis-setups-configs
  kafka:
    consumer:
      auto-offset-reset: earliest
    # change this property if you are using your own Kafka cluster or your Docker IP is different
    bootstrap-servers: ${kafka:localhost:9092}
    client-id: gis-setups-service
  security:
    oauth2:
      resource:
        id: geminia
        token-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token
        authorization-uri: ${app.auth.server.realm-url}/protocol/openid-connect/auth
        userinfo-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
        token-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token/introspect
        user-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.server.realm-url}
          jwk-set-uri: ${app.auth.server.realm-url}/protocol/openid-connect/certs
  flyway:
    locations: classpath:/db/migration/oracle
    baseline-on-migrate: false #NEVER CHANGE BASELINE TO TRUE
    validate-on-migrate: false #true to populate local DB
    table: schema_version
    enabled: true
    out-of-order: true
    ignore-migration-patterns: false
  quartz:
    job-store-type: jdbc
    enabled: false
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
            driverDelegateClass: 'org.quartz.impl.jdbcjobstore.StdJDBCDelegate'
            class: 'org.quartz.impl.jdbcjobstore.JobStoreTXthreadPool'
            tablePrefix: 'QRTZ_'
            selectWithLockSQL: 'SELECT * FROM {0}LOCKS WHERE SCHED_NAME = {1} AND LOCK_NAME = ? FOR UPDATE'
          threadPool:
            threadCount: 5
  sql:
    init:
      mode: always
defaultTenant: turnquest
# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.176.18.211:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
instanceId: gis-setups-service-instance
env: environment

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{tenantId:-gis}] %-5level %logger{36} - %msg%n'
  level:
    com:
      turnkey:
        turnquest: DEBUG
    org:
      #      springframework:
      #        security: debug
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    name: gis-setups-service.log
    path: ./logs

management:
  endpoints:
    web:
      exposure:
        include: "*"

turnquest:
  api:
    basePath:
      v1: "/api/v1"
      v2: "/api/v2"
  clients:
    crm-setups:
      base-url: http://crm-setups-service
    crm-accounts:
      base-url: http://crm-accounts-service
    crm:
      base-url: http://crm-accounts-service
    crm-useradmin:
      base-url: http://crm-user-administration-service
    setups:
      base-url: http://gis-setups-service
    premium-computation-engine:
      base-url: http://premium-computation-service
    notification-service:
      base-url: http://turnquest-notification-service
    underwriting-service:
      base-url: http://gis-underwriting-service
    quotation-service:
      base-url: http://gis-quotation-service
    alfresco-service:
      base-url: http://turnquest-alfresco-service

multitenancy:
  defaultTenant: turnquest
  include: turnquest,v6test,heritage19c
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_CRM
        password: CRM_2026
        driver-class-name: oracle.jdbc.OracleDriver

