spring:
  profiles:
    active: dev
  # from application-common.yml
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.server.realm-url}
          jwk-set-uri: ${app.auth.server.realm-url}/protocol/openid-connect/certs
  redis:
    host: ${REDIS_HOST:10.176.18.211}
    port: ${REDIS_PORT:6380}
  messages:
    basename: i18n/messages
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false # from application-dev.yml
    base-url: ${ZIPKIN_URL:http://10.176.18.211:9411}
  mvc:
    format:
      date: yyyy-MM-dd
  mail:
    host: ${SMTP_HOST:your-smtp-host.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:your-email@example.com}
    password: ${SMTP_PASSWORD:your-email-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  # from application-fmsMessagingService.yml
  application:
    name: FMS-MESSAGING-SERVICE

server:
  port: 2008 # from application-fmsMessagingService.yml
  error:
    include-message: always
  servlet:
    context-path: /
tq:
  dateTimeFormat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - beans
          - env
          - loggers
          - mappings
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://10.176.18.211:8761/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true} # from application-dev.yml
    fetch-registry: true # from application-dev.yml
app:
  auth:
    server:
      realm-url: ${KEYCLOAK_URL:http://10.176.18.211:8181/realms/turnquest-version-six}
      jwk-set-uri: ${KEYCLOAK_URL:http://10.176.18.211:8181/realms/turnquest-version-six}/protocol/openid-connect/certs
  rolesClaim: roles
  cors:
    allowed-origins: "http://localhost:2001"
  locale:
    languages: "en, fr, sw"
    baseName: i18n/messages
    defaultLang: en
  base_url: /api/v1
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    org:
      hibernate: OFF
meta:
  whatsapp:
    api-version: "v23.0"
    phone-number-id: ${META_WHATSAPP_PHONE_NUMBER_ID}
    access-token: ${META_WHATSAPP_SYSTEM_USER_TOKEN}
