server:
  forward-headers-strategy: framework
  port: 4001
  servlet:
    context-path: /
  error:
    include-message: always
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "prometheus", "bindings", "beans", "env", "loggers", "streamsbindings", "mappings","flyway" ] # Combined and kept as is

app:
  name: TurnQuest Version Vi Integrated GIS Underwriting System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: https://evolve.keycloak.caavagroup.com/realms/geminia
  rolesClaim: roles
  locale:
    baseName: i18n/messages
    defaultLang: en
  quotation-endpoints:
    list-quotations: /quotations
    quotation-risks: "/quotationRisks/{code}"
  setups-endpoints:
    get-parameter-by-param-name-endpoint: /parameters/parameter-name
    get-tax-type-views-endpoint: /taxes-types-view
    get-product-by-id-endpoint: "/products/{code}"
    get-clause-by-id-endpoint: "/clauses/{code}"
    get-subclass-by-id-endpoint: "/sub-classes/{code}"
    get-parameters-list-endpoint: /parameters/list/parameter-name
    get-binder-by-code: "/binders/{code}"
    get-commission-transactions-endpoint: "/commission-rates/commission-transactions"
    get-screen-name-endpoint: /screens/name
    get-populate-lien-clauses: "/populate-clauses"
    getAllSubclassCertTypesEndpoint: "/subclass-cert-types/all"
    getSubclassCertTypesBySectionEndpoint: "/subclass-cert-types/section"
    find-subclass-cert-type-endpoint: /subclass-cert-types
    find-binders-for-ins-endpoint: /binders/ins
    find-manual-binders-for-non-ins-endpoint: /binders/manual-non-ins
    get-potential-docs-endpoint: /required-documents/for-transaction
    get-fetch-schedule-values-by-subclass-endpoint: "/schedule-values/bySubclass"
    get-fetch-schedule-values-by-subclass-and-bind-endpoint: "schedule-values/sclCode-bindCode"
    get-mandatory-sections: "/premium-rates/mandatory-sections"
    get-cash-back-sections: "/premium-rates/cash-back-sections"
    get-cover-type-default-s-i: "/subclass-cover-types/default-SI"
    get-risk-limits: "/premium-rates/risk-limits"
    get-product-subclasses-count: "product-subclasses/count-product-subclasses/{code}"
    get-premium-rates: "/premium-rates/all-rates"
    get-section-rates: "/premium-rates/section-rates"
    mandatory-unassigned-clauses-endpoint: "/subclass-clauses/mandatory-unassigned"
    get-subclass-section-peril-details-endpoint: /subclass-section-perils/details
    get-count-driver-endpoint: "/driver-details/count"
    get-find-driver-code-endpoint: "/driver-details/find"
    get-add-driver-endpoint: "/driver-details/add"
    get-find-driver-details-by-code-endpoint: "/driver-details/code"
    get-count-driver-by-code: "/driver-details/count/code"
    get-delete-driver-endpoint: "/driver-details/driver-details/count/code"
    fetch-subclass-section-perils-endpoint: /subclass-section-perils/subclassSectionPerilsMap
    bouquet-premium-rates-endpoint: /premium-rates/bouquet-rates
    fetch-class-treaties-by-subclass-code-endpoint: /class-treaties

    get-subclass-by-class-code: "/sub-classes/by-class-code/{code}"
    get-cover-type-details: "/subclass-cover-types/details"
    get-policy-clauses: "/subclass-clauses/policy-clauses"
    get-clauses-not-in-policy: "/subclass-clauses/clauses-not-in-policy"
    get-clauses-with-policy: "/subclass-clauses/clauses-with-policy"
    get-product-subclasses-count-endpoint: "/products/product-subclasses-count"
    get-lien-clauses-by-product-code: "/clauses/lien-clauses"
    fetch-risk-categories-endpoint: /risk-categories
    fetch-perils-by-subclass-bind-and-section: "/subperils//by-subclass-bind-section"
    fetch-risk-services-list-endpoint: /risk-service
    fetch-risk-subclass-section-peril-endpoint: /subclass-section-perils/risk
    fetch-premium-rates-details: /premium-rates/details
    fetch-taxes-applicable: "/taxes-types-view/applicable"
    fetch-transaction-codes-by-category: "/transaction-types/codes-by-category"
    fetch-premium-rate-details: "/premium-rates/details"
    get-lien-clauses-not-in-policy: "/subclass-clauses/lien-clauses-not-in-policy"
    get-policy-lien-clauses: "/subclass-clauses/policy-lien-clauses"
    fetch-product-subclass-taxes-endpoint: /taxes-types-view/product-subclass-taxes
    get-special-premium-rates-by-section-endpoint: /special-premium-rates/by-section
    get-available-perils-endpoint: /perils/available
    fetch-clauses-for-population: /clauses/by-subclass-product-code
    get-multi-class-clauses-endpoint: /clauses/product/multi-class
    get-clauses-by-subclasses-endpoint: /clauses/product/subclasses
    get-count-mandatory-clauses-endpoint: /subclass-clauses/count
    find-cover-types-by-code-endpoint: "/cover-types/{code}"
    fetch-section-endpoint: "sections/{code}"
    count-product-and-product-group-endpoint: "/products/product-count"
    fetch-cover-type-details-endpoint: /subclass-covertype-to-sections/details

  commons-endpoints:
    save-transaction-details-endpoint: "/gis-transactions"
    generate-number-format-endpoint: /number-format/generate
    get-master-transaction-summary-endpoint: /master-transactions/summary
    generate-certificate-number-endpoint: /number-format/certificate
    save-transmittal-details-endpoint: /transmittal
    fetch-paid-premium-endpoint: /master-transactions/premium
    get-get-transactions-by-batch-no-endpoint: /batchNo
    get-mandatory-clause-global-exception-count-endpoint: /gis-exceptions/count
  crm-setups-endpoints:
    get-org-type-endpoint: "/organizations/organization-by-system/{system-code}/"
    find-agency-list-by-code-endpoint: /agents/fetchAllById
    fetch-intermediary-list-endpoint: /v2/api/intermediary/
    get-systems-by-agent-code-endpoint: "/agents/{agentCode}/agency-systems/"
    find-client-list-by-code-endpoint: /v2/api/clients/list-detailed


spring:
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE # From first configuration
  messages:
    basename: i18n/messages
  application:
    name: gis-underwriting-service
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  cloud:
    config:
      import-check:
        enabled: false
      server:
        git:
          uri: https://github.com/turnkeyafrica/turnquest-v6
          searchPaths: gis-reinsurance-configs
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka:localhost:9092}
    client-id: gis-underwriting-service
  security:
    oauth2:
      resource:
        id: geminia
        token-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token
        authorization-uri: ${app.auth.server.realm-url}/protocol/openid-connect/auth
        userinfo-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
        token-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token/introspect
        user-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.server.realm-url}
          jwk-set-uri: ${app.auth.server.realm-url}/protocol/openid-connect/certs
  flyway:
    locations: classpath:/db/migration/oracle
    baseline-on-migrate: false #NEVER CHANGE BASELINE TO TRUE
    validate-on-migrate: false #true to populate local DB
    table: schema_version
    enabled: true
    ignore-missing-migrations: false
    out-of-order: true
  quartz:
    job-store-type: jdbc
    enabled: false
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
            driverDelegateClass: 'org.quartz.impl.jdbcjobstore.StdJDBCDelegate'
            class: 'org.quartz.impl.jdbcjobstore.JobStoreTXthreadPool'
            tablePrefix: 'QRTZ_'
            selectWithLockSQL: 'SELECT * FROM {0}LOCKS WHERE SCHED_NAME = {1} AND LOCK_NAME = ? FOR UPDATE'
          threadPool:
            threadCount: 5
  sql:
    init:
      mode: always

defaultTenant: turnquest
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
    instances:
      crmService:
        baseConfig: default
      setupsService:
        baseConfig: default
      premiumComputationService:
        baseConfig: default
      notificationClient:
        baseConfig: default


#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 3
#    prefer-ip-address: true
#  client:
#    enabled: false
#    serviceUrl:
#      defaultZone: http://192.0.0.169:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true

instanceId: gis-underwriting-service-instance
env: environment

management:
  zipkin:
    tracing:
      endpoint: http://10.176.18.27:9411
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    mappings:
      enabled: true

logging:
  file:
    name: gis-underwriting-service.log
    path: ./logs
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


turnquest:
  api:
    basePath:
      v1: "/api/v1"
      v2: "/api/v2"
  clients:
    crm:
      base-url: https://evolve.api.dev.caavagroup.com/crm
      setupsService: https://evolve.api.dev.caavagroup.com/crm/setups
      setups: https://evolve.api.dev.caavagroup.com/crm/setups

    crm-setups:
      base-url: https://evolve.api.dev.caavagroup.com/crm/setups

    crm-accounts:
      base-url: https://evolve.api.dev.caavagroup.com/crm/accounts

    crm-useradmin:
      base-url: https://evolve.api.dev.caavagroup.com/user/administration

    setups:
      base-url: https://evolve.api.dev.caavagroup.com/gis/setups/api/v1   # originally had /api/v1

    premium-computation-engine:
      base-url: https://evolve.api.dev.caavagroup.com/premium/computation

    notification-service:
      base-url: https://evolve.api.dev.caavagroup.com/turnquest/notification

    underwriting-service:
      base-url: https://evolve.api.dev.caavagroup.com/gis/underwriting

    commons-service:
      base-url: https://evolve.api.dev.caavagroup.com/gis/commons/api/v1   # originally had /api/v1

    ticketing-service:
      base-url: https://evolve.api.dev.caavagroup.com/gis/ticketing/api/v1 # originally had /api/v1

    quotation-service:
      base-url: https://evolve.api.dev.caavagroup.com/gis/quotation

    alfresco-service:
      base-url: http://alfresco-service   # ❗ not in gateway
      
    reinsurance-service:
      base-url: https://evolve.api.dev.caavagroup.com/gis/reinsurance/api/v1

    claim-service:
      base-url: https://evolve.api.dev.caavagroup.com/gis/claims/api/v1
      
    gis:
      setups:
        service: https://evolve.api.dev.caavagroup.com/gis/setups



feign:
  client:
    config:
      premium-computation-engine:
        url: http://10.176.18.211:4020


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: GIS UNDERWRITING API
  # server-url: /gis/underwriting

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_GIS
        password: GIS_2026
        driver-class-name: oracle.jdbc.OracleDriver
#    heritage:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.91:1521/HERITAGE
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
#    heritage19c:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.91:1522/heritage19c
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
#    v6test:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.70:18000/TQV6
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
#    geminia:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.99:1521/EVOLVE_GEMINIA
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
