spring:
  sleuth:
    sampler:
      probability: 1.0
  messages:
    basename: i18n/messages
  application:
    name: quotation-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    initialization-mode: always
    hikari:
      idle-timeout: 300000
      max-lifetime: 1800000
      allow-pool-suspension: true
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  management:
    zipkin:
      tracing:
        endpoint: http://10.176.18.211:9411

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_HOST:kafka.service.consul}:${SPRING_KAFKA_PORT:9092}
    consumer:
      auto-offset-reset: earliest
    client-id: gis-quotation-service
  security:
    oauth2:
      resource:
        id: geminia
        token-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token
        authorization-uri: ${app.auth.server.realm-url}/protocol/openid-connect/auth
        userinfo-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
        token-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/token/introspect
        user-info-uri: ${app.auth.server.realm-url}/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.server.realm-url}
          jwk-set-uri: ${app.auth.server.realm-url}/protocol/openid-connect/certs
  flyway:
    locations: classpath:/db/migration/oracle
    baseline-on-migrate: false
    validate-on-migrate: false
    table: schema_version
    enabled: false
    ignore-missing-migrations: false
    out-of-order: true
  quartz:
    job-store-type: jdbc
    enabled: false
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
            driverDelegateClass: 'org.quartz.impl.jdbcjobstore.StdJDBCDelegate'
            class: 'org.quartz.impl.jdbcjobstore.JobStoreTXthreadPool'
            tablePrefix: 'QRTZ_'
            selectWithLockSQL: 'SELECT * FROM {0}LOCKS WHERE SCHED_NAME = {1} AND LOCK_NAME = ? FOR UPDATE'
          threadPool:
            threadCount: 5
  redis:
    cache:
      type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis.service.consul}
      port: ${SPRING_REDIS_PORT:6379}
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
    instances:
      crmService:
        baseConfig: default
      setupsService:
        baseConfig: default
      premiumComputationService:
        baseConfig: default
      notificationClient:
        baseConfig: default
      underwritingClient:
        baseConfig: default
      commonsClient:
        baseConfig: default


server:
  port: 4007
  servlet:
    context-path: /
  error:
    include-message: always
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "prometheus", "bindings", "beans", "env", "loggers", "streamsbindings", "mappings","flyway" ]

app:
  name: TurnQuest Version Vi Integrated GIS Underwriting System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: http://10.176.18.211:8181/realms/turnquest-version-six
  rolesClaim: roles
  locale:
    baseName: i18n/messages
    defaultLang: en
  setups-endpoints:
    find-subclass-cover-type-by-cover-type-code-endpoint: "/subclass-cover-types/coverType/{coverTypeCode}"
    fetch-excesses-endpoint: /excess
    get-product-by-id-endpoint: "/products/{code}"
    get-clause-by-id-endpoint: "/clauses/{code}"
    get-subclass-by-id-endpoint: "/sub-classes/{code}"
    get-product-expiry-endpoint: "/products/{code}"
    get-product-taxes-endpoint: /product-taxes
    get-parameter-value-endpoint: /parameters/parameter-name
    mandatory-clauses-endpoint: /clauses/mandatory
    find-clause-wording-endpoint: /clauses/wording

defaultTenant: turnquest

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://10.176.18.211:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

instanceId: quotation-service-instance
env: environment

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    name: quotation-service.log
    path: ./logs

turnquest:
  api:
    basePath:
      v1: "/api/v1"
      v2: "/api/v2"
  clients:
    crm-setups:
      base-url: http://crm-setups-service
    crm:
      base-url: http://crm-accounts-service
    crm-accounts:
      base-url: http://crm-accounts-service
    crm-useradmin:
      base-url: http://crm-user-administration-service
    setups:
      base-url: http://gis-setups-service
    premium-computation-engine:
      base-url: http://gis-premium-computation-service
    notification-service:
      base-url: http://turnquest-notification-service
    underwriting-service:
      base-url: http://gis-underwriting-service
    quotation-service:
      base-url: http://gis-quotation-service
    alfresco-service:
      base-url: http://turnquest-alfresco-service

feign:
  client:
    config:
      premium-computation-engine:
        url: http://10.176.18.211:4020

multitenancy:
  defaultTenant: turnquest
  include: turnquest,v6test,heritage19c
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_GIS
        password: GIS_2026
        driver-class-name: oracle.jdbc.OracleDriver
#    heritage:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.91:1521/HERITAGE
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
#    heritage19c:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.91:1522/heritage19c
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
#    v6test:
#      datasource:
#        url: jdbc:oracle:thin:@10.176.18.70:18000/TQV6
#        username: TQ_GIS
#        password: TQ_GIS
#        driver-class-name: oracle.jdbc.OracleDriver
