server:
  forward-headers-strategy: framework
  port: 9990

management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
