app:
  auth:
    server:
      realm-url: ${KEYCLOAK_REALM_URL:https://evolve.staging.caavagroup.com/realms/geminia}

spring:
  cloud:
    config:
      enabled: false
  application:
    name: turnquest-workflow-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia
          jwk-set-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/certs

camunda.bpm:
  admin-user:
    id: ${CAMUNDA_ADMIN_USER:admin}
    password: ${CAMUNDA_ADMIN_PASSWORD:admin}
    database.schema-update: true
  filter:
    create: All tasks
  webapp:
    application-path: /turnquest-workflow

server:
  forward-headers-strategy: framework
  port: 1027

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_CRM
        password: CRM_2026
        driver-class-name: oracle.jdbc.OracleDriver
