debug: false
logging:
  level: INFO
  level.root: INFO
  level.com.netflix.discovery: "OFF"
  level.com.netflix.eureka: "OFF"
  level.org.hibernate.SQL: "OFF"
  level.org.hibernate.type: "OFF"
  level.org.apache.kafka: "INFO"
  level.c.t.t.g.s.c.RequestAndResponseLoggingFilter: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

server:
  port: 4015

springdoc:
  swagger-ui:
    path: "/gateway/swagger-ui.html"

spring:
  application:
    name: gis-gateway

  cloud:
    kubernetes:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: quotation-service
          uri: lb://quotation-service
          predicates:
            - Path=/quotes/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-setups-service
          uri: lb://gis-setups-service
          predicates:
            - Path=/setups/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-underwriting-service
          uri: lb://gis-underwriting-service
          predicates:
            - Path=/policies/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-claims-service
          uri: lb://gis-claims-service
          predicates:
            - Path=/claims/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-reinsurance-service
          uri: lb://gis-reinsurance-service
          predicates:
            - Path=/reinsurance/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-commons-service
          uri: lb://gis-commons-service
          predicates:
            - Path=/commons/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: premium-computation-service
          uri: lb://premium-computation-service
          predicates:
            - Path=/premium/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-ticketing-service
          uri: lb://gis-ticketing-service
          predicates:
            - Path=/tickets/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-migration-service
          uri: lb://gis-migration-service
          predicates:
            - Path=/migration/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: gis-payment-service
          uri: lb://gis-payment-service
          predicates:
            - Path=/payments/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}