server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/provisioning_jobs
    username: provisioning_user
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092

tenant-registry:
  base-url: http://tenant-registry-service:8080/api/v1

provisioning:
  saas:
    postgresql:
      host: postgres-shared.internal
      port: 5432
      admin-username: postgres
      admin-password: ${POSTGRES_ADMIN_PASSWORD}

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

logging:
  level:
    root: DEBUG
