spring:
  sleuth:
    sampler:
      probability: 1.0
  # jackson:
  #   property-naming-strategy: SNAKE_CASE
  messages:
    basename: i18n/messages
  application:
    name: fms-cash-book-transactions-service
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  datasource:
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  management:
    zipkin:
      tracing:
        endpoint: http://10.176.18.27:9411
  cloud:
    config:
      import-check:
        enabled: false
      server:
        git:
          uri: https://github.com/turnkeyafrica/turnquest-v6
          searchPaths: gis-setups-configs
    kubernetes:
      discovery:
        enabled: true      
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: ${kafka:localhost:9092}
    client-id: gis-setups-service
  security:
    oauth2:
      resource:
        id: turnquest-version-6-apis
        token-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/token
        authorization-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/auth
        userinfo-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/userinfo
        token-info-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/token/introspect
      resourceserver:
        jwt:
          issuer-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia
          jwk-set-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/certs
  flyway:
    locations: classpath:/db/migration/oracle
    baseline-on-migrate: false
    validate-on-migrate: false
    table: schema_version
    enabled: true
    ignore-missing-migrations: false
    out-of-order: true
  quartz:
    job-store-type: jdbc
    enabled: false
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            tablePrefix: QRTZ_
            selectWithLockSQL: "SELECT * FROM {0}LOCKS WHERE SCHED_NAME = {1} AND LOCK_NAME = ? FOR UPDATE"
          threadPool:
            threadCount: 5
server:
  forward-headers-strategy: framework
  port: 2009
  servlet:
    context-path: /
  error:
    include-message: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - bindings
          - beans
          - env
          - loggers
          - streamsbindings
          - mappings
          - flyway
app:
  name: TurnQuest Version Vi Integrated FMS Setups System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: ${KEYCLOAK_URL:https://evolve.staging.caavagroup.com/realms/geminia}
      jwk-set-uri: ${KEYCLOAK_URL:https://evolve.staging.caavagroup.com/realms/geminia}/protocol/openid-connect/certs
  rolesClaim: roles
  # cors:
  #   allowed-origins: "http://localhost:2003,http://localhost:4200,http://192.0.0.169,https://evolve.dev.caavagroup.com"  
  locale:
    languages: "en, fr, sw"  # Add new languages in the format ",vi"
    baseName: i18n/messages
    defaultLang: en
base_url: /api/v1
# eureka:
#   instance:
#     leaseRenewalIntervalInSeconds: 1
#     leaseExpirationDurationInSeconds: 3
#     prefer-ip-address: true
#   client:
#     serviceUrl:
#       defaultZone: http://192.0.0.169:8761/eureka/
#     fetch-registry: true
#     register-with-eureka: true
instanceId: fms-setups-service-instance
env: environment
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    com:
      turnkey:
        turnquest: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#  file:
#    name: fms-setups-service.log
#    path: ./logs
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - bindings
          - beans
          - env
          - loggers
          - streamsbindings
          - mappings
          - flyway
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_FMS
        password: FMS_2026
        driver-class-name: oracle.jdbc.OracleDriver


redis:
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis.service.consul}
      port: ${SPRING_REDIS_PORT:6379}
# These keys should match the 'name' you use in @FeignClient
# Format: http://[kubernetes-service-name]:[port]
turnquest:
  clients:
    # --- CRM Services ---
    crm-user-administration-service: http://crm-user-administration-service:8080
    crm-setups-service: http://crm-setups-service:8080
    crm-accounts-service: http://crm-accounts-service:8080
    turnquest-chart-service: http://turnquest-chart-service:8080

    # --- FMS Services ---
    fms-setups-service: http://fms-setups-service:8080
    fms-receipting-service: http://fms-receipting-service:8080
    fms-payment-service: http://fms-payment-service:8080
    fms-fixed-assets-service: http://fms-fixed-assets-service:8080
    fms-general-ledger-service: http://fms-general-ledger-service:8080
    fms-investments-service: http://fms-investments-service:8080
    fms-messaging-service: http://fms-messaging-service:8080
    fms-cash-book-transactions-service: http://fms-cash-book-transactions-service:8080

    # --- GIS Services ---
    gis-setups-service: http://gis-setups-service:8080
    gis-underwriting-service: http://gis-underwriting-service:8080
    gis-payment-service: http://gis-payment-service:8080
    gis-quotation-service: http://gis-quotation-service:8080
    gis-claims-service: http://gis-claims-service:8080
    gis-commons-service: http://gis-commons-service:8080
    gis-ticketing-service: http://gis-ticketing-service:8080

    # --- Core / Shared Services ---
    turnquest-notification-service: http://turnquest-notification-service:8080
    turnquest-ticketing-service: http://turnquest-ticketing-service:8080
    turnquest-report-service: http://turnquest-report-service:8080
    turnquest-workflow-service: http://turnquest-workflow-service:8080
    data-etl-service: http://data-etl-service:8080
    premium-computation-service: http://premium-computation-service:8080

    # --- Other Departments (Banca, LMS) ---
    banca-setups-service: http://banca-setups-service:8080
    lms-setups-service: http://lms-setups-service:8080
    lms-marketing-service: http://lms-marketing-service:8080 