spring:
  # from application-common.yml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none # from application-dev.yml
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        order_by:
          default_null_ordering: last
      generate-ddl: true
      show-sql: true
  flyway:
    locations: classpath:db/migration/oracle
    baseline-on-migrate: true
    ignore-missing-migrations: true
    out-of-order: true
    table: schema_version
    enabled: false
  cloud:
    config:
      enabled: false
    kubernetes:
      discovery:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.server.realm-url}
          jwk-set-uri: ${app.auth.server.realm-url}/protocol/openid-connect/certs
  # redis:
  #   host: ${REDIS_HOST:10.176.18.211}
  #   port: ${REDIS_PORT:6380}
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
            class: org.quartz.simpl.SimpleThreadPool
          scheduler:
            instanceId: AUTO
            instanceName: V6ServiceScheduler
  messages:
    basename: i18n/messages
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false # from application-dev.yml
    base-url: ${ZIPKIN_URL:http://10.176.18.27:9411}
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  sql:
    init:
      mode: always
  # from application-fmsReceiptingService.yml
  application:
    name: fms-receipting-service

server:
  forward-headers-strategy: framework
  port: 2001 # from application-fmsReceiptingService.yml
  error:
    include-message: always
  servlet:
    context-path: /
tq:
  dateTimeFormat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - bindings
          - beans
          - env
          - loggers
          - streamsbindings
          - mappings
          - flyway
feign:
  client:
    config:
      default: # Use default to apply to ALL feign clients
        connectTimeout: 6000
        logger-level: basic
        requestInterceptors:
          - com.turnkey.turnquest.common.multitenancy.MultiTenantFeignClientInterceptor
app:
  auth:
    server:
      realm-url: ${KEYCLOAK_URL:https://evolve.keycloak.caavagroup.com/realms/geminia}
      jwk-set-uri: ${KEYCLOAK_URL:https://evolve.keycloak.caavagroup.com/realms/geminia}/protocol/openid-connect/certs
  rolesClaim: roles
  # cors:
  #   allowed-origins: "http://localhost:2003,http://localhost:4200,http://192.0.0.169,https://evolve.dev.caavagroup.com"
  locale:
    languages: "en, fr, sw"
    baseName: i18n/messages
    defaultLang: en
base_url: /api/v1
alfresco:
  api:
    url: http://10.176.18.101:9080/alfrescoServices
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    feign:
      client: DEBUG
    # from application-fmsReceiptingService.yml
    com.turnkey.turnquest.feigns.*: DEBUG
multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_FMS
        password: FMS_2026
        driver-class-name: oracle.jdbc.OracleDriver
redis:
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis.service.consul}
      port: ${SPRING_REDIS_PORT:6379}
# Configuration for resiliently fetching reports      
report-fetching:
  retry:
    max-attempts: 5
    initial-backoff-ms: 1000
    max-backoff-ms: 10000
# These keys should match the 'name' you use in @FeignClient
# Format: http://[kubernetes-service-name]:[port]
turnquest:
  clients:
    # --- CRM Services ---
    crm-user-administration-service: http://crm-user-administration-service:8080
    crm-setups-service: http://crm-setups-service:8080
    crm-accounts-service: http://crm-accounts-service:8080
    turnquest-chart-service: http://turnquest-chart-service:8080

    # --- FMS Services ---
    fms-setups-service: http://fms-setups-service:8080
    fms-receipting-service: http://fms-receipting-service:8080
    fms-payment-service: http://fms-payment-service:8080
    fms-fixed-assets-service: http://fms-fixed-assets-service:8080
    fms-general-ledger-service: http://fms-general-ledger-service:8080
    fms-investments-service: http://fms-investments-service:8080
    fms-messaging-service: http://fms-messaging-service:8080
    fms-cash-book-transactions-service: http://fms-cash-book-transactions-service:8080

    # --- GIS Services ---
    gis-setups-service: http://gis-setups-service:8080
    gis-underwriting-service: http://gis-underwriting-service:8080
    gis-payment-service: http://gis-payment-service:8080
    gis-quotation-service: http://gis-quotation-service:8080
    gis-claims-service: http://gis-claims-service:8080
    gis-commons-service: http://gis-commons-service:8080
    gis-ticketing-service: http://gis-ticketing-service:8080

    # --- Core / Shared Services ---
    turnquest-notification-service: http://turnquest-notification-service:8080
    turnquest-ticketing-service: http://turnquest-ticketing-service:8080
    turnquest-report-service: http://turnquest-report-service:8080
    turnquest-workflow-service: http://turnquest-workflow-service:8080
    data-etl-service: http://data-etl-service:8080
    premium-computation-service: http://premium-computation-service:8080

    # --- Other Departments (Banca, LMS) ---
    banca-setups-service: http://banca-setups-service:8080
    lms-setups-service: http://lms-setups-service:8080
    lms-marketing-service: http://lms-marketing-service:8080    
