server:
  forward-headers-strategy: framework
  port: 1036

app:
  name: TurnQuest Version Vi Charts Service
  auth:
    server:
      realm-url: ${KEYCLOAK_REALM_URL:https://evolve.keycloak.caavagroup.com/realms/geminia}

spring:
  application:
    name: chart-services
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.server.realm-url}
          jwk-set-uri: ${app.auth.server.realm-url}/protocol/openid-connect/certs

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

logging:
  file:
    name: chart-service.log
    path: ./logs

locale:
  baseName: messages
  defaultLang: en

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_CRM
        password: CRM_2026
        driver-class-name: oracle.jdbc.OracleDriver
