spring:
  application:
    name: gis-migration-service
  datasource:
    url: jdbc:oracle:thin:@//190.0.2.231:1521/evolve_staging
    username: TQ_GIS
    password: GIS_2026
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    show-sql: true

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolve_staging
        username: TQ_GIS
        password: GIS_2026
        driver-class-name: oracle.jdbc.OracleDriver
