spring:
  application:
    name: turnquest-gateway-service
  main:
    web-application-type: reactive
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    config:
      import-check:
        enabled: false
      uri: http://10.176.18.211:1026
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: swagger
          predicates:
            - Path=/v2/api-docs/**
          filters:
            - RewritePath=/v2/api-docs/(?<path>.*), /$\{path}/v2/api-docs
          uri: http://localhost:${server.port}
        - id: crm-setups-service
          uri: lb://CRM-SETUPS-SERVICE
          predicates:
            - Path=/crm/setups/**
          filters:
            - StripPrefix=2
        - id: crm-accounts-service
          uri: lb://CRM-ACCOUNTS-SERVICE
          predicates:
            - Path=/crm/accounts/**
          filters:
            - StripPrefix=2
        - id: banca-setups-service
          uri: lb://BANCA-SETUPS-SERVICE
          predicates:
            - Path=/banca/setups/**
          filters:
            - StripPrefix=2
        - id: lms-setups-service
          uri: lb://LMS-SETUPS-SERVICE
          predicates:
            - Path=/lms/setups/**
          filters:
            - StripPrefix=2
        - id: lms-marketing-service
          uri: lb://LMS-MARKETING-SERVICE
          predicates:
            - Path=/lms/marketing/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
    database-platform: org.hibernate.dialect.H2Dialect
 # configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://10.176.18.211:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 1025
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,flyway
  endpoint:
    health:
      show-details: always
app:
  name: TurnQuest Version Vi Gateway Service
  configurations:
    password-strength: 3
    password-length: 6
    
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
resilience4j:
  circuitbreaker:
    instances:
      crm-setups-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
      crm-accounts-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
      banca-setups-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
      lms-setups-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
      lms-marketing-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
      swagger:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED  