server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://turnquest-discovery-service/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway
app:
  name: TurnQuest Version Vi Discovery Service
  configurations:
    password-strength: 3
    password-length: 6
spring:
  application:
    name: turnquest-discovery-service
  cloud:
    config:
      uri: http://10.176.18.211:1026
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE