server:
  forward-headers-strategy: framework
  port: 9991

app:
  base-url: ${APP_BASE_URL}
  auth:
    server:
      realm-url: https://evolve.staging.caavagroup.com/realms/geminia

reports:
  deployed:
    path: ${REPORTS_DEPLOYED_PATH}
  individual:
    path: ${REPORTS_INDIVIDUAL_PATH}
  group:
    path: ${REPORTS_GROUP_PATH}
  gis:
    path: src/resources/reports/gis
  crm:
    path: ${REPORTS_CRM_PATH}

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis-service}
      port: ${SPRING_REDIS_PORT:6379}

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_CRM
        password: CRM_2026
        driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org:
      hibernate:
        SQL: INFO
