server:
  forward-headers-strategy: framework
  port: 9991

app:
  base-url: https://evolve.api.dev.caavagroup.com/turnquest/report
  auth:
    server:
      realm-url: https://evolve.keycloak-uat.caavagroup.com/realms/geminia

reports:
  deployed:
    path: /tqv6vol/APIS/TQ-V6/reports
  individual:
    path: /tqv6vol/APIS/TQ-V6/lms/Reports/individual
  group:
    path: /tqv6vol/APIS/TQ-V6/lms/Reports/group
  gis:
    path: reports/gis
  crm:
    path: /tqv6vol/APIS/TQ-V6/lms/Reports/crm

spring:
  data:
    redis:
      host: redis-service
      port: 6379

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:18034/evolve_uat
        username: TQ_CRM
        password: CRM_2026
        driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
