spring:
  application:
    name: database-migration-service

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
        change-log-file: db/turnquest/changelog-master.xml

logging:
  level:
    liquibase: INFO

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false
