server:
  port: 1041

app:
  auth:
    server:
      realm-url: ${KEYCLOAK_REALM_URL}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org:
      hibernate:
        SQL: INFO
