server:
  port: 1041

app:
  auth:
    server:
      realm-url: https://evolve.keycloak.caavagroup.com/realms/geminia

spring:
  datasource:
    url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
    username: TQ_GIS
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
