server:
  forward-headers-strategy: framework
  port: 1041

app:
  auth:
    server:
      realm-url: https://evolve.keycloak-staging.caavagroup.com/realms/geminia

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

# Kubernetes client disabled - OkHttp conflict with Africa's Talking SDK
spring.cloud.kubernetes:
  enabled: false
  config:
    enabled: false
  discovery:
    enabled: false
  loadbalancer:
    enabled: false

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org:
      hibernate:
        SQL: INFO
