server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: WARN
