server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: evolve-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
