server:
  forward-headers-strategy: framework
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tenant_registry
    username: registry_user
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

spring.cloud.kubernetes:
  discovery:
    enabled: true
    all-namespaces: false

logging:
  level:
    root: DEBUG
