server:
  forward-headers-strategy: framework
  port: 1038

app:
  name: TurnQuest Version Vi Integrated User Administration System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: https://evolve.staging.caavagroup.com/realms/geminia
  rolesClaim: roles

spring:
  application:
    name: user-administration-service
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia
          jwk-set-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/certs

logging:
  file:
    name: user-administration-service.log
    path: ./logs

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolvedb_dev
        username: TQ_CRM
        password: CRM_2026
        driver-class-name: oracle.jdbc.OracleDriver
      notification:
        enabled: true
    heritage:
      datasource:
        url: jdbc:oracle:thin:@10.176.18.91:1521/HERITAGE
        username: TQ_CRM
        password: TQ_CRM
        driver-class-name: oracle.jdbc.OracleDriver
    v6test:
      datasource:
        url: jdbc:oracle:thin:@10.176.18.70:18000/TQV6
        username: TQ_CRM
        password: TQ_CRM
        driver-class-name: oracle.jdbc.OracleDriver
      notification:
        enabled: true
    lifeco:
      datasource:
        url: jdbc:oracle:thin:@10.176.18.139:1521/LIFECO_INT
        username: TQ_CRM
        password: TQ_CRM
        driver-class-name: oracle.jdbc.OracleDriver
      notification:
        enabled: true
    mutual:
      datasource:
        url: jdbc:oracle:thin:@10.176.18.9:1522/MUTUALDB
        username: TQ_CRM
        password: TQ_CRM
        driver-class-name: oracle.jdbc.OracleDriver
      notification:
        enabled: true
    fidelity:
      datasource:
        url: jdbc:oracle:thin:@10.176.18.138:1522/FIDINT
        username: TQ_CRM
        password: TQ_CRM
        driver-class-name: oracle.jdbc.OracleDriver
      notification:
        enabled: true
    test:
      datasource:
        url: jdbc:h2:mem:testdb;MODE=Oracle
        username: sa
        password: password
        driver-class-name: org.h2.Driver
        initialization-mode: never
        database-platform: org.hibernate.dialect.H2Dialect

locale:
  baseName: messages
  defaultLang: en
