server:
  forward-headers-strategy: framework
  port: 1038

app:
  name: TurnQuest Version Vi Integrated User Administration System
  configurations:
    password-strength: 3
    password-length: 6
  auth:
    server:
      realm-url: https://evolve.staging.caavagroup.com/realms/geminia
  rolesClaim: roles

spring:
  application:
    name: user-administration-service
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia
          jwk-set-uri: https://evolve.keycloak-staging.caavagroup.com/realms/geminia/protocol/openid-connect/certs

logging:
  file:
    name: user-administration-service.log
    path: ./logs

multitenancy:
  defaultTenant: turnquest
  include: turnquest
  tenants:
    turnquest:
      datasource:
        url: jdbc:oracle:thin:@//190.0.2.231:1521/evolve_staging
        username: TQ_CRM
        password: CRM_2026
        driver-class-name: oracle.jdbc.OracleDriver

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /user/administration/v3/api-docs/swagger-config
    url: /user/administration/v3/api-docs
    urls:
      - url: /user/administration/v3/api-docs
        name: User Administrations API

locale:
  baseName: messages
  defaultLang: en
